Add optional chaining operator to response
wakatime/atom-wakatime pull request #111
Opened 2021-07-24 21:43 UTC by gandarez

This PR adds optional chaining operator to `response` in order to not throw any error when response is null.

Fixes https://github.com/wakatime/atom-wakatime/issues/110

2021-07-24 21:56 UTC, aminya requested changes
If you are using optional chaining make sure to use Babel to support older Atom versions

2021-07-25 03:13 UTC, gandarez commented
> If you are using optional chaining make sure to use Babel to support older Atom versions

The first line of js files is `'use babel';`. Does that work?

2021-07-25 04:35 UTC, aminya commented
Atom uses Babel 5 at the moment. That doesn't include the recently added optional chaining.

2021-07-25 04:36 UTC, aminya requested changes

2021-07-25 04:36 UTC, aminya commented on lib/wakatime.js
> +                log.warn(`GitHub API Response ${response?.statusCode}: ${error}`);
```suggestion
                log.warn(`GitHub API Response ${"statusCode" in response ? response.statusCode : ""}: ${error}`);
```

2021-07-25 21:38 UTC, gandarez commented
Thanks for the suggestion @aminya

2021-08-14 21:54 UTC, alanhamlett approved these changes

2021-08-14 23:17 UTC, merged